language: generic
sudo: false
env:
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-git-snapshot-travis
before_install:
  - export PATH=$HOME/.evm/bin:$HOME/.cask/bin:$PATH
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - evm config path /tmp
install:
  - evm install $EVM_EMACS --use --skip
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
script:
  - make all
