language: generic

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - EVM_EMACS=emacs-25.2-travis
        
before_install:
  - export PATH=$HOME/.evm/bin:$HOME/.cask/bin:$PATH
  - curl -fsSL https://raw.github.com/rejeep/evm/master/go | bash
  - evm config path /tmp

install:
  - evm install $EVM_EMACS --use --skip
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python

script:
  - make all
